/*
 * Copyright (c) 2019-2026, NVIDIA CORPORATION.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-FileCopyrightText: Copyright (c) 2019-2026, NVIDIA CORPORATION.
 * SPDX-License-Identifier: Apache-2.0
 */

//
// GPU-accelerated skeletal skinning and morph target blending via compute
// shaders. Static per-primitive data (base geometry, skin weights/joints,
// inverse bind matrices, morph deltas) is uploaded once at scene load as
// GPU SSBOs. Each frame, only the small per-skin joint matrices and
// per-morph weights are uploaded; compute shaders then write the results
// directly into the existing SceneVk vertex buffers via BDA pointers.
//

#include "gltf_scene_animation_vk.hpp"
#include "gltf_scene_animation.hpp"
#include "tinygltf_utils.hpp"

#include <nvvk/check_error.hpp>
#include <nvvk/debug_util.hpp>
#include <nvvk/barriers.hpp>
#include <nvutils/logger.hpp>
#include <nvutils/timers.hpp>
#include <tinygltf/tiny_gltf.h>
#include <cassert>
#include <span>

// Pre-compiled compute shaders (generated by CMake's compile_slang)
#include "_autogen/skinning.comp.slang.h"
#include "_autogen/morph.comp.slang.h"

namespace nvvkgltf {

namespace {
constexpr const char* kMemCategorySkinning = "Skinning";
constexpr const char* kMemCategoryMorphing = "Morphing";
}  // namespace

//--------------------------------------------------------------------------------------------------
// Initialize compute pipelines for skinning and morph blending.
void AnimationVk::init(nvvk::ResourceAllocator* alloc)
{
  m_alloc = alloc;
  m_memoryTracker.init(alloc);
  createPipelines();
}

//--------------------------------------------------------------------------------------------------
// Release all GPU resources and pipelines.
void AnimationVk::deinit()
{
  if(!m_alloc)
    return;
  destroyGpuBuffers();
  destroyPipelines();
  m_alloc = nullptr;
}

//--------------------------------------------------------------------------------------------------
// Create the skinning and morph compute pipelines. Each uses only push constants
// (no descriptor sets) since all buffer addresses are passed via BDA pointers.
void AnimationVk::createPipelines()
{
  VkDevice device = m_alloc->getDevice();

  // Skinning pipeline (push constants only, no descriptor sets)
  {
    VkPushConstantRange pushRange{.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT, .offset = 0, .size = sizeof(shaderio::SkinPushConstant)};
    VkPipelineLayoutCreateInfo layoutInfo{.sType                  = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO,
                                          .pushConstantRangeCount = 1,
                                          .pPushConstantRanges    = &pushRange};
    NVVK_CHECK(vkCreatePipelineLayout(device, &layoutInfo, nullptr, &m_skinPipelineLayout));
    NVVK_DBG_NAME(m_skinPipelineLayout);

    VkShaderModuleCreateInfo shaderInfo{.sType    = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
                                        .codeSize = skinning_comp_slang_sizeInBytes,
                                        .pCode    = skinning_comp_slang};

    VkComputePipelineCreateInfo pipeInfo{.sType  = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
                                         .stage  = {.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
                                                    .pNext = &shaderInfo,
                                                    .stage = VK_SHADER_STAGE_COMPUTE_BIT,
                                                    .pName = "main"},
                                         .layout = m_skinPipelineLayout};
    NVVK_CHECK(vkCreateComputePipelines(device, nullptr, 1, &pipeInfo, nullptr, &m_skinPipeline));
    NVVK_DBG_NAME(m_skinPipeline);
  }

  // Morph pipeline
  {
    VkPushConstantRange pushRange{.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT, .offset = 0, .size = sizeof(shaderio::MorphPushConstant)};
    VkPipelineLayoutCreateInfo layoutInfo{.sType                  = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO,
                                          .pushConstantRangeCount = 1,
                                          .pPushConstantRanges    = &pushRange};
    NVVK_CHECK(vkCreatePipelineLayout(device, &layoutInfo, nullptr, &m_morphPipelineLayout));
    NVVK_DBG_NAME(m_morphPipelineLayout);

    VkShaderModuleCreateInfo shaderInfo{.sType    = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
                                        .codeSize = morph_comp_slang_sizeInBytes,
                                        .pCode    = morph_comp_slang};

    VkComputePipelineCreateInfo pipeInfo{.sType  = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
                                         .stage  = {.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
                                                    .pNext = &shaderInfo,
                                                    .stage = VK_SHADER_STAGE_COMPUTE_BIT,
                                                    .pName = "main"},
                                         .layout = m_morphPipelineLayout};

    NVVK_CHECK(vkCreateComputePipelines(device, nullptr, 1, &pipeInfo, nullptr, &m_morphPipeline));
    NVVK_DBG_NAME(m_morphPipeline);
  }
}

//--------------------------------------------------------------------------------------------------
// Destroy compute pipelines and layouts.
void AnimationVk::destroyPipelines()
{
  VkDevice device = m_alloc->getDevice();
  if(m_skinPipeline)
    vkDestroyPipeline(device, m_skinPipeline, nullptr);
  if(m_morphPipeline)
    vkDestroyPipeline(device, m_morphPipeline, nullptr);
  if(m_skinPipelineLayout)
    vkDestroyPipelineLayout(device, m_skinPipelineLayout, nullptr);
  if(m_morphPipelineLayout)
    vkDestroyPipelineLayout(device, m_morphPipelineLayout, nullptr);
  m_skinPipeline        = {};
  m_morphPipeline       = {};
  m_skinPipelineLayout  = {};
  m_morphPipelineLayout = {};
}

//========== Buffer Helpers ==========

static constexpr VkBufferUsageFlags2 kSsboUsage =
    VK_BUFFER_USAGE_2_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_2_SHADER_DEVICE_ADDRESS_BIT | VK_BUFFER_USAGE_2_TRANSFER_DST_BIT;

//--------------------------------------------------------------------------------------------------
// Create a GPU SSBO and stage its initial data for upload. Returns a null buffer if byteSize is 0.
nvvk::Buffer AnimationVk::createBufferFromData(nvvk::StagingUploader& staging, const void* data, size_t byteSize, const char* debugName)
{
  nvvk::Buffer buf;
  if(byteSize == 0)
    return buf;
  NVVK_CHECK(m_alloc->createBuffer(buf, byteSize, kSsboUsage));
  if(debugName)
    NVVK_DBG_NAME(buf.buffer);
  staging.appendBuffer(buf, 0, byteSize, data);
  return buf;
}

template <typename T>
nvvk::Buffer AnimationVk::createBufferFromSpan(nvvk::StagingUploader& staging, std::span<const T> data, const char* debugName)
{
  return createBufferFromData(staging, data.data(), data.size_bytes(), debugName);
}

//========== Static GPU Buffer Creation (once at scene load) ==========

//--------------------------------------------------------------------------------------------------
// Upload all static animation data to GPU SSBOs. Called once when the scene is loaded or rebuilt.
// For skinning: base geometry, skin weights, joint indices, and inverse bind matrices per primitive.
// For morphing: base geometry and all morph target deltas packed sequentially per primitive.
void AnimationVk::createGpuBuffers(nvvk::StagingUploader& staging, const Scene& scn)
{
  destroyGpuBuffers();

  const auto& skinTasks    = scn.animation().getSkinTasks();
  const auto& morphResults = scn.animation().getMorphPrimitives();
  const auto& model        = scn.getModel();

  // Skin GPU buffers: one set of SSBOs per unique skinned primitive (SkinTask).
  // Also compute offsets for the packed per-frame joint/normal matrix buffers.
  size_t totalJointMatBytes  = 0;
  size_t totalNormalMatBytes = 0;
  m_skinGpuData.resize(skinTasks.size());
  for(size_t i = 0; i < skinTasks.size(); i++)
  {
    const SkinTask& task = skinTasks[i];
    SkinGpuData&    gpu  = m_skinGpuData[i];

    size_t numJoints =
        (task.skinID >= 0 && task.skinID < static_cast<int>(model.skins.size())) ? model.skins[task.skinID].joints.size() : 0;

    if(task.inverseBindMatrices.size() < numJoints)
    {
      const char* skinName = (task.skinID >= 0) ? model.skins[task.skinID].name.c_str() : "?";
      LOGW("Skin '%s': inverseBindMatrices count (%zu) < joint count (%zu); missing entries default to identity\n",
           skinName, task.inverseBindMatrices.size(), numJoints);
    }

    gpu.basePositions       = createBufferFromSpan(staging, std::span<const glm::vec3>(task.basePositions));
    gpu.baseNormals         = createBufferFromSpan(staging, std::span<const glm::vec3>(task.baseNormals));
    gpu.baseTangents        = createBufferFromSpan(staging, std::span<const glm::vec4>(task.baseTangents));
    gpu.weights             = createBufferFromSpan(staging, std::span<const glm::vec4>(task.weights));
    gpu.joints              = createBufferFromSpan(staging, std::span<const glm::ivec4>(task.joints));
    gpu.inverseBindMatrices = createBufferFromSpan(staging, std::span<const glm::mat4>(task.inverseBindMatrices));

    m_memoryTracker.track(kMemCategorySkinning, gpu.basePositions.allocation);
    m_memoryTracker.track(kMemCategorySkinning, gpu.baseNormals.allocation);
    m_memoryTracker.track(kMemCategorySkinning, gpu.baseTangents.allocation);
    m_memoryTracker.track(kMemCategorySkinning, gpu.weights.allocation);
    m_memoryTracker.track(kMemCategorySkinning, gpu.joints.allocation);
    m_memoryTracker.track(kMemCategorySkinning, gpu.inverseBindMatrices.allocation);

    gpu.jointMatOffset  = totalJointMatBytes;
    gpu.normalMatOffset = totalNormalMatBytes;
    totalJointMatBytes += numJoints * sizeof(glm::mat4);
    totalNormalMatBytes += numJoints * sizeof(glm::mat3);
  }

  // Pre-allocate packed per-frame buffers for all skin tasks' joint + normal matrices
  if(totalJointMatBytes > 0)
  {
    NVVK_CHECK(m_alloc->createBuffer(m_jointMatricesBuffer, totalJointMatBytes, kSsboUsage));
    m_memoryTracker.track(kMemCategorySkinning, m_jointMatricesBuffer.allocation);
  }
  if(totalNormalMatBytes > 0)
  {
    NVVK_CHECK(m_alloc->createBuffer(m_normalMatricesBuffer, totalNormalMatBytes, kSsboUsage));
    m_memoryTracker.track(kMemCategorySkinning, m_normalMatricesBuffer.allocation);
  }

  // Morph GPU buffers: base geometry + packed deltas for all targets per morph primitive.
  // Delta layout in GPU memory: [target0_vertex0..target0_vertexN, target1_vertex0..target1_vertexN, ...]
  size_t      totalMorphWeightsBytes = 0;
  const auto& morphResultsVec        = scn.animation().getMorphPrimitives();
  m_morphGpuData.resize(morphResultsVec.size());
  for(size_t mi = 0; mi < morphResultsVec.size(); mi++)
  {
    const MorphResult& mr  = scn.animation().getMorphResult(mi);
    MorphGpuData&      gpu = m_morphGpuData[mi];

    gpu.basePositions = createBufferFromSpan(staging, std::span<const glm::vec3>(mr.basePositions));
    gpu.baseNormals   = createBufferFromSpan(staging, std::span<const glm::vec3>(mr.baseNormals));
    gpu.baseTangents  = createBufferFromSpan(staging, std::span<const glm::vec4>(mr.baseTangents));

    m_memoryTracker.track(kMemCategoryMorphing, gpu.basePositions.allocation);
    m_memoryTracker.track(kMemCategoryMorphing, gpu.baseNormals.allocation);
    m_memoryTracker.track(kMemCategoryMorphing, gpu.baseTangents.allocation);

    // Pack all morph target deltas sequentially: [target0_v0..target0_vN, target1_v0..target1_vN, ...]
    if(mr.renderPrimID >= 0)
    {
      const RenderPrimitive&     renderPrim = scn.getRenderPrimitive(mr.renderPrimID);
      const tinygltf::Primitive& primitive  = *renderPrim.pPrimitive;
      const tinygltf::Mesh&      mesh       = model.meshes[renderPrim.meshID];

      uint32_t numTargets = static_cast<uint32_t>(std::min(primitive.targets.size(), mesh.weights.size()));
      std::vector<glm::vec3> allPosDeltas;
      std::vector<glm::vec3> allNrmDeltas;
      std::vector<glm::vec3> allTanDeltas;

      bool hasNormalDeltas  = false;
      bool hasTangentDeltas = false;

      for(uint32_t t = 0; t < numTargets; t++)
      {
        const auto& target = primitive.targets[t];

        // Position deltas
        auto posFind = target.find("POSITION");
        if(posFind != target.end() && posFind->second >= 0 && posFind->second < static_cast<int>(model.accessors.size()))
        {
          std::vector<glm::vec3> temp;
          std::span<const glm::vec3> deltas = tinygltf::utils::getAccessorData(model, model.accessors[posFind->second], &temp);
          allPosDeltas.insert(allPosDeltas.end(), deltas.begin(), deltas.end());
        }
        else
        {
          allPosDeltas.resize(allPosDeltas.size() + mr.basePositions.size(), glm::vec3(0));
        }

        // Normal deltas
        auto nrmFind = target.find("NORMAL");
        if(nrmFind != target.end() && nrmFind->second >= 0 && nrmFind->second < static_cast<int>(model.accessors.size()))
        {
          std::vector<glm::vec3> temp;
          std::span<const glm::vec3> deltas = tinygltf::utils::getAccessorData(model, model.accessors[nrmFind->second], &temp);
          allNrmDeltas.insert(allNrmDeltas.end(), deltas.begin(), deltas.end());
          hasNormalDeltas = true;
        }
        else
        {
          allNrmDeltas.resize(allNrmDeltas.size() + mr.basePositions.size(), glm::vec3(0));
        }

        // Tangent deltas
        auto tanFind = target.find("TANGENT");
        if(tanFind != target.end() && tanFind->second >= 0 && tanFind->second < static_cast<int>(model.accessors.size()))
        {
          std::vector<glm::vec3> temp;
          std::span<const glm::vec3> deltas = tinygltf::utils::getAccessorData(model, model.accessors[tanFind->second], &temp);
          allTanDeltas.insert(allTanDeltas.end(), deltas.begin(), deltas.end());
          hasTangentDeltas = true;
        }
        else
        {
          allTanDeltas.resize(allTanDeltas.size() + mr.basePositions.size(), glm::vec3(0));
        }
      }

      gpu.numTargets    = numTargets;
      gpu.weightsOffset = totalMorphWeightsBytes;
      totalMorphWeightsBytes += numTargets * sizeof(float);
      gpu.positionDeltas = createBufferFromSpan(staging, std::span<const glm::vec3>(allPosDeltas));
      m_memoryTracker.track(kMemCategoryMorphing, gpu.positionDeltas.allocation);
      if(hasNormalDeltas && !mr.baseNormals.empty())
      {
        gpu.normalDeltas = createBufferFromSpan(staging, std::span<const glm::vec3>(allNrmDeltas));
        m_memoryTracker.track(kMemCategoryMorphing, gpu.normalDeltas.allocation);
      }
      if(hasTangentDeltas && !mr.baseTangents.empty())
      {
        gpu.tangentDeltas = createBufferFromSpan(staging, std::span<const glm::vec3>(allTanDeltas));
        m_memoryTracker.track(kMemCategoryMorphing, gpu.tangentDeltas.allocation);
      }
    }
  }

  // Pre-allocate packed per-frame buffer for all morph tasks' weights
  if(totalMorphWeightsBytes > 0)
  {
    NVVK_CHECK(m_alloc->createBuffer(m_morphWeightsBuffer, totalMorphWeightsBytes, kSsboUsage));
    m_memoryTracker.track(kMemCategoryMorphing, m_morphWeightsBuffer.allocation);
  }
}

//--------------------------------------------------------------------------------------------------
// Release all GPU SSBOs (static and per-frame workspace). Safe to call even if no buffers exist.
void AnimationVk::destroyGpuBuffers()
{
  if(!m_alloc)
    return;

  auto destroySkin = [this](nvvk::Buffer& buf) {
    if(buf.buffer != VK_NULL_HANDLE)
    {
      m_memoryTracker.untrack(kMemCategorySkinning, buf.allocation);
      m_alloc->destroyBuffer(buf);
    }
    buf = {};
  };

  auto destroyMorph = [this](nvvk::Buffer& buf) {
    if(buf.buffer != VK_NULL_HANDLE)
    {
      m_memoryTracker.untrack(kMemCategoryMorphing, buf.allocation);
      m_alloc->destroyBuffer(buf);
    }
    buf = {};
  };

  for(auto& gpu : m_skinGpuData)
  {
    destroySkin(gpu.basePositions);
    destroySkin(gpu.baseNormals);
    destroySkin(gpu.baseTangents);
    destroySkin(gpu.weights);
    destroySkin(gpu.joints);
    destroySkin(gpu.inverseBindMatrices);
  }
  m_skinGpuData.clear();

  for(auto& gpu : m_morphGpuData)
  {
    destroyMorph(gpu.basePositions);
    destroyMorph(gpu.baseNormals);
    destroyMorph(gpu.baseTangents);
    destroyMorph(gpu.positionDeltas);
    destroyMorph(gpu.normalDeltas);
    destroyMorph(gpu.tangentDeltas);
  }
  m_morphGpuData.clear();

  destroySkin(m_jointMatricesBuffer);
  destroySkin(m_normalMatricesBuffer);
  destroyMorph(m_morphWeightsBuffer);
}

//========== Per-Frame Dispatch ==========

//--------------------------------------------------------------------------------------------------
// Record compute shader dispatches for the current animation frame.
//
// For each morph primitive: uploads the current morph weights, then dispatches the morph compute
// shader which blends base geometry + weighted deltas -> output vertex buffer.
//
// For each skinned primitive: computes joint matrices on CPU (invNode * worldJoint * IBM), uploads
// them via staging, then dispatches the skinning compute shader which transforms base geometry
// using 4 joint influences per vertex -> output vertex buffer.
//
// All output is written directly into SceneVk's existing vertex buffers via BDA pointers.
// A shared per-frame matrix/weights buffer is reused across tasks with proper barriers.
//
// After all dispatches, a final barrier ensures the written vertex data is visible to
// subsequent vertex input and acceleration structure build stages.
void AnimationVk::dispatchAnimation(VkCommandBuffer cmd, nvvk::StagingUploader& staging, Scene& scn, const SceneVk& scnVk)
{
  const tinygltf::Model&        model        = scn.getModel();
  const std::vector<glm::mat4>& nodeMatrices = scn.getNodesWorldMatrices();
  const auto&                   vertexBufs   = scnVk.vertexBuffers();
  const auto&                   skinTasks    = scn.animation().getSkinTasks();

  // === Phase 1: Batch-upload all per-frame data (morph weights + joint/normal matrices) ===

  // Pack all morph weights into the pre-allocated buffer at per-task offsets
  for(size_t mi = 0; mi < m_morphGpuData.size(); mi++)
  {
    const MorphGpuData& gpu = m_morphGpuData[mi];
    const MorphResult&  mr  = scn.animation().getMorphResult(mi);
    if(mr.renderPrimID < 0 || mr.basePositions.empty() || gpu.numTargets == 0)
      continue;

    const auto&           renderPrim = scn.getRenderPrimitive(mr.renderPrimID);
    const tinygltf::Mesh& mesh       = model.meshes[renderPrim.meshID];

    std::vector<float> weights(gpu.numTargets, 0.0f);
    uint32_t           safeCount = std::min(gpu.numTargets, static_cast<uint32_t>(mesh.weights.size()));
    if(safeCount < gpu.numTargets)
    {
      LOGW("Morph prim %zu: mesh.weights count (%zu) < gpu.numTargets (%u); extra targets will use weight 0\n", mi,
           mesh.weights.size(), gpu.numTargets);
    }
    for(uint32_t t = 0; t < safeCount; t++)
      weights[t] = static_cast<float>(mesh.weights[t]);

    assert(gpu.weightsOffset + weights.size() * sizeof(float) <= m_morphWeightsBuffer.bufferSize);
    staging.appendBuffer(m_morphWeightsBuffer, gpu.weightsOffset, std::span(weights));
  }

  // Compute and pack all joint + normal matrices into pre-allocated buffers at per-task offsets
  for(size_t ti = 0; ti < skinTasks.size(); ti++)
  {
    const SkinTask&    task = skinTasks[ti];
    const SkinGpuData& gpu  = m_skinGpuData[ti];

    if(task.skinID < 0 || task.skinID >= static_cast<int>(model.skins.size()))
      continue;
    if(task.refNodeID < 0 || task.refNodeID >= static_cast<int>(nodeMatrices.size()))
      continue;

    const tinygltf::Skin& skin      = model.skins[task.skinID];
    const size_t          numJoints = skin.joints.size();

    std::vector<glm::mat4> jointMats(numJoints);
    std::vector<glm::mat3> normalMats(numJoints);
    glm::mat4              invNode = glm::inverse(nodeMatrices[task.refNodeID]);
    for(size_t i = 0; i < numJoints; ++i)
    {
      int jointNodeID = skin.joints[i];
      if(jointNodeID < 0 || jointNodeID >= static_cast<int>(nodeMatrices.size()))
        continue;
      jointMats[i] = invNode * nodeMatrices[jointNodeID]
                     * (i < task.inverseBindMatrices.size() ? task.inverseBindMatrices[i] : glm::mat4(1));
      normalMats[i] = glm::transpose(glm::inverse(glm::mat3(jointMats[i])));
    }

    assert(gpu.jointMatOffset + jointMats.size() * sizeof(glm::mat4) <= m_jointMatricesBuffer.bufferSize);
    assert(gpu.normalMatOffset + normalMats.size() * sizeof(glm::mat3) <= m_normalMatricesBuffer.bufferSize);
    staging.appendBuffer(m_jointMatricesBuffer, gpu.jointMatOffset, std::span(jointMats));
    staging.appendBuffer(m_normalMatricesBuffer, gpu.normalMatOffset, std::span(normalMats));
  }

  // Single transfer + single barrier for all per-frame data
  staging.cmdUploadAppended(cmd);
  nvvk::cmdMemoryBarrier(cmd, VK_PIPELINE_STAGE_2_TRANSFER_BIT, VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
                         VK_ACCESS_2_TRANSFER_WRITE_BIT, VK_ACCESS_2_SHADER_READ_BIT);

  // === Phase 2: Dispatch all morph compute shaders ===
  if(!m_morphGpuData.empty())
  {
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, m_morphPipeline);

    for(size_t mi = 0; mi < m_morphGpuData.size(); mi++)
    {
      const MorphGpuData& gpu = m_morphGpuData[mi];
      const MorphResult&  mr  = scn.animation().getMorphResult(mi);
      if(mr.renderPrimID < 0 || mr.basePositions.empty() || gpu.numTargets == 0)
        continue;

      const auto& vb = vertexBufs[mr.renderPrimID];

      shaderio::MorphPushConstant pc{};
      pc.basePositions  = reinterpret_cast<glm::vec3*>(gpu.basePositions.address);
      pc.baseNormals    = gpu.baseNormals.buffer ? reinterpret_cast<glm::vec3*>(gpu.baseNormals.address) : nullptr;
      pc.baseTangents   = gpu.baseTangents.buffer ? reinterpret_cast<glm::vec4*>(gpu.baseTangents.address) : nullptr;
      pc.positionDeltas = reinterpret_cast<glm::vec3*>(gpu.positionDeltas.address);
      pc.normalDeltas   = gpu.normalDeltas.buffer ? reinterpret_cast<glm::vec3*>(gpu.normalDeltas.address) : nullptr;
      pc.tangentDeltas  = gpu.tangentDeltas.buffer ? reinterpret_cast<glm::vec3*>(gpu.tangentDeltas.address) : nullptr;
      pc.morphWeights   = reinterpret_cast<float*>(m_morphWeightsBuffer.address + gpu.weightsOffset);
      pc.outPositions   = reinterpret_cast<glm::vec3*>(vb.position.address);
      pc.outNormals = (vb.normal.buffer && gpu.baseNormals.buffer) ? reinterpret_cast<glm::vec3*>(vb.normal.address) : nullptr;
      pc.outTangents = (vb.tangent.buffer && gpu.baseTangents.buffer) ? reinterpret_cast<glm::vec4*>(vb.tangent.address) : nullptr;
      pc.vertexCount = static_cast<uint32_t>(mr.basePositions.size());
      pc.numTargets  = gpu.numTargets;

      vkCmdPushConstants(cmd, m_morphPipelineLayout, VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(pc), &pc);
      vkCmdDispatch(cmd, (pc.vertexCount + ANIMATION_WORKGROUP_SIZE - 1) / ANIMATION_WORKGROUP_SIZE, 1, 1);
    }
  }

  // === Phase 3: Dispatch all skinning compute shaders ===
  if(!m_skinGpuData.empty())
  {
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, m_skinPipeline);

    for(size_t ti = 0; ti < skinTasks.size(); ti++)
    {
      const SkinTask&    task = skinTasks[ti];
      const SkinGpuData& gpu  = m_skinGpuData[ti];

      if(task.skinID < 0 || task.skinID >= static_cast<int>(model.skins.size()))
        continue;
      if(task.refNodeID < 0 || task.refNodeID >= static_cast<int>(nodeMatrices.size()))
        continue;
      if(!gpu.basePositions.buffer || !gpu.weights.buffer || !gpu.joints.buffer)
        continue;

      const tinygltf::Skin& skin = model.skins[task.skinID];
      const auto&           vb   = vertexBufs[task.renderPrimID];

      shaderio::SkinPushConstant pc{};
      pc.basePositions  = reinterpret_cast<glm::vec3*>(gpu.basePositions.address);
      pc.baseNormals    = gpu.baseNormals.buffer ? reinterpret_cast<glm::vec3*>(gpu.baseNormals.address) : nullptr;
      pc.baseTangents   = gpu.baseTangents.buffer ? reinterpret_cast<glm::vec4*>(gpu.baseTangents.address) : nullptr;
      pc.weights        = reinterpret_cast<glm::vec4*>(gpu.weights.address);
      pc.joints         = reinterpret_cast<glm::ivec4*>(gpu.joints.address);
      pc.jointMatrices  = reinterpret_cast<glm::mat4*>(m_jointMatricesBuffer.address + gpu.jointMatOffset);
      pc.normalMatrices = reinterpret_cast<glm::mat3*>(m_normalMatricesBuffer.address + gpu.normalMatOffset);
      pc.outPositions   = reinterpret_cast<glm::vec3*>(vb.position.address);
      pc.outNormals     = vb.normal.buffer ? reinterpret_cast<glm::vec3*>(vb.normal.address) : nullptr;
      pc.outTangents    = vb.tangent.buffer ? reinterpret_cast<glm::vec4*>(vb.tangent.address) : nullptr;
      pc.vertexCount    = static_cast<uint32_t>(task.weights.size());
      pc.numJoints      = static_cast<uint32_t>(skin.joints.size());

      vkCmdPushConstants(cmd, m_skinPipelineLayout, VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(pc), &pc);
      vkCmdDispatch(cmd, (pc.vertexCount + ANIMATION_WORKGROUP_SIZE - 1) / ANIMATION_WORKGROUP_SIZE, 1, 1);
    }
  }

  // Barrier: compute writes -> vertex input + AS build
  nvvk::cmdMemoryBarrier(cmd, VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
                         VK_PIPELINE_STAGE_2_VERTEX_INPUT_BIT | VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_BUILD_BIT_KHR,
                         VK_ACCESS_2_SHADER_WRITE_BIT,
                         VK_ACCESS_2_VERTEX_ATTRIBUTE_READ_BIT | VK_ACCESS_2_ACCELERATION_STRUCTURE_READ_BIT_KHR);
}

}  // namespace nvvkgltf
